version: 2
jobs:
  upload:
    working_directory: ~/repo
    docker:
      - image: circleci/node:10.15-jessie-browsers
    steps:
      - checkout

      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm-wee
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          command: CONFIG_FIREBASE=echo $firebase | base64 --decode
      - run:
          name: Run firebase script
          command: node .circleci/firebase-script.js $CONFIG_FIREBASE
workflows:
  version: 2
  upload:
    jobs:
      - upload:
          filters:
            branches:
              only: master